# permissions for end users to view nginx24664s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx24664-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - nginx24664s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - nginx24664s/status
  verbs:
  - get
