# permissions for end users to view nginx24644s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx24644-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - nginx24644s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - nginx24644s/status
  verbs:
  - get
