# permissions for end users to edit nginxolms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxolm-editor-role
rules:
- apiGroups:
  - olm.example.com
  resources:
  - nginxolms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.example.com
  resources:
  - nginxolms/status
  verbs:
  - get
