# permissions for end users to view memcachedolmtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedolmtest-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcachedolmtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcachedolmtests/status
  verbs:
  - get
